name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.0-beta2"
          stable: "false"

      - name: Check format
        run: |
          unformatted="$(gofmt -l .)"
          [ -z "$unformatted" ] || {
            echo "Unformatted files are found." >&2
            echo "$unformatted" | sed -E 's/^/  /' >&2
            exit 1
          }

  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18.0-beta2"
          stable: "false"

      - name: Test
        run: go test -v ./...
